baseURL = "https://rickymoorhouse.uk/"
languageCode = "en-gb"
title = "Ricky Moorhouse"
theme = "rickymoorhouse"
disqusShortname = "" # delete this to disable disqus comments
[params]
    author = "Ricky Moorhouse"
    description = "I'm a Christian, living in Portsmouth with my lovely wife Laura and our 2 fantastic daughters Abi & Jessica. With a background in system management and security I currently lead the UK part of a worldwide cloud operations team that support a number of IBM SaaS offerings."
    githubUsername = "rickymoorhouse"
    accent = "#009988"
    showBorder = true
    backgroundColor = "white"
#    font = "Alegreya" # should match the name on Google Fonts!
    copyright = "&copy; Ricky Moorhouse"
    highlight = true
    highlightLanguages = ["python", "swift", "YAML"]

#  js = ["https://api.mapbox.com/mapbox.js/v0.44.2/mapbox.js"]
#  css = ["https://api.mapbox.com/mapbox.js/v0.44.2/mapbox.css"]
#[[menu.main]]
#    url = "/"
#    name = "Home"
#    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/travel/"
    name = "Travel"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/rickymoorhouse/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rickymoorhouse/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rickymoorhouse/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/rickymoorhouse/"
    name = "instagram"
    weight = 3
