baseURL = "https://rickymoorhouse.uk/"
languageCode = "en-gb"
title = "Ricky Moorhouse"
theme = "rickymoorhouse"
disqusShortname = "" # delete this to disable disqus comments
pluralizelisttitles = false
[permalinks]
  blog = "/blog/:year/:slug/"

[params]
    author = "Ricky Moorhouse"
    description = "I live in the south of England with my wife and daughters. I work at IBM on the hosted API Connect cloud services. I enjoy running, walking, photography and spending time with my family."
    githubUsername = "rickymoorhouse"
    build = "main"
    accent = "#869ba0"
    secondary = "#d2bba2"
    backgroundColor = "black"
    showBorder = true
    dateFormat = "2 January 2006"
    images = ["images/siteicon.png"]
#    font = "Alegreya" # should match the name on Google Fonts!
    copyright = "&copy; Ricky Moorhouse"
    highlight = true
    highlightLanguages = ["python", "javascript", "yaml"]
[languages]
  [languages.en]
    title = "Ricky Moorhouse"
  [languages.es]
    title = "Ricky Moorhouse en Español"
    description = "Vivo en el sur de Inglaterra con mi esposa y hijas. Yo trabajo en las ofertas de nube de IBM API Connect. Me gusta corriendo, caminando, fotografia y passando tiempo con mi familia."
[[menu.main]]
    url = "/travel/"
    name = "Travel"
    weight = 3
[[menu.main]]
    url = "/photos/"
    name = "Photos"
    weight = 4
[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 4
[[menu.main]]
    url = "/weather/"
    name = "Weather"
    weight = 5

[[languages.es.menu.main]]
    url = "/es/viaje/"
    name = "Viaje"
    weight = 3
[[languages.es.menu.main]]
    url = "/photos/"
    name = "Fotos"
    weight = 4
[[languages.es.menu.main]]
    url = "/es/meteo/"
    name = "Meteo"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/rickymoorhouse/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rickymoorhouse/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rickymoorhouse/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/rickymoorhouse/"
    name = "instagram"
    weight = 3

[[languages.es.menu.icon]]
    url = "https://github.com/rickymoorhouse/"
    name = "github"
    weight = 2

[[languages.es.menu.icon]]
    url = "https://twitter.com/rickymoorhouse/"
    name = "twitter"
    weight = 3

[[languages.es.menu.icon]]
    url = "https://www.linkedin.com/in/rickymoorhouse/"
    name = "linkedin"
    weight = 4

[[languages.es.menu.icon]]
    url = "https://www.instagram.com/rickymoorhouse/"
    name = "instagram"
[markup.goldmark.renderer]
unsafe= true

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "s3"
URL = "s3://blog.rickymoorhouse.co.uk?region=eu-west-1"
cloudFrontDistributionID = "E23ZIB9AOTAEC9"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

