name: Hugo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get hugo
      run: |
        curl -LO https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.tar.gz
        tar -vzxf hugo_0.73.0_Linux-64bit.tar.gz
        chmod a+x hugo

    - name: Build
      run: ./hugo

       
