---
name: Hugo
on: push
jobs:

  build:
    name: Build-site
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Get hugo
        env:
          HUGO_VERSION: "0.133.0"
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
      - name: Set build ref
        if: github.ref != 'refs/heads/main'
        run: |
          sed -i 's/build = "main"/build = "preview"/' config.yaml
          sed -i 's/rickymoorhouse.uk/drafts.rickymoorhouse.uk/' config.yaml

      - name: Build
        run: $HOME/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "public"
          destination: "www"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.STORAGE_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"  

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blog-content
          path: |
             public
