name: Hugo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get hugo
      run: |
        curl -LO https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.tar.gz
        tar -vzxf hugo_0.73.0_Linux-64bit.tar.gz
        chmod a+x hugo

    - name: Build
      run: ./hugo

    - name: SSH setup
      env:
        DEPLOY_KEY: ${{ secrets.ssh_private_key }}
        KNOWN_HOSTS: ${{ secrets.known_hosts }}
      run: |
        mkdir -p ~/.ssh
        echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
        chmod -R 700 ~/.ssh
    - name: Rsync deployment
      run: |
        rsync -e 'ssh -p 22022' -arvz public/* github@graphite.rickymoorhouse.uk:/var/www/rickymoorhouse.uk/
