name: Hugo
on: [push]
jobs:

  build:
    name: Build-draft
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get hugo
      run: |
        curl -LO https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_0.73.0_Linux-64bit.tar.gz
        tar -vzxf hugo_0.73.0_Linux-64bit.tar.gz
        chmod a+x hugo

    - name: Set build ref
      if: if: github.ref != 'refs/heads/master'
      run: sed -i s/build = "main"/build = "preview"/ config.toml

    - name: Build
      run: ./hugo

    - name: SSH setup
      env:
        DEPLOY_KEY: ${{ secrets.ssh_private_key }}
        KNOWN_HOSTS: ${{ secrets.known_hosts }}
      run: |
        mkdir -p ~/.ssh
        echo "${DEPLOY_KEY}" > ~/.ssh/rsync_key
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        chmod -R 700 ~/.ssh
    - name: Rsync deployment
      run: |
        rsync -e 'ssh -p 22022 -i ~/.ssh/rsync_key' -arvz --no-t public/* github@graphite.rickymoorhouse.uk:/var/www/rickymoorhouse.uk/
